export const ADMIN_NAV_ITEMS = [
  { href: '/panel/dashboard', label: 'Dashboard', icon: 'home', roles: ['ADMIN', 'ADMIN_WORKER'] },
  { href: '/panel/users', label: 'Usuarios', icon: 'user', roles: ['ADMIN', 'ADMIN_WORKER'] },
  { href: '/panel/quizzes', label: 'Quizzes', icon: 'quiz', roles: ['ADMIN', 'ADMIN_WORKER'] },
  { href: '/panel/kyc', label: 'KYC', icon: 'shield', roles: ['ADMIN'] },
  { href: '/panel/payments', label: 'Pagos', icon: 'card', roles: ['ADMIN'] },
  { href: '/panel/financial', label: 'Finanzas', icon: 'money', roles: ['ADMIN'] },
  { href: '/panel/seasons', label: 'Temporadas', icon: 'trophy', roles: ['ADMIN'] },
  { href: '/panel/quiz-distribution', label: 'Reparto Quiz', icon: 'chart', roles: ['ADMIN'] },
  { href: '/panel/season-jackpot-distribution', label: 'Reparto Jackpot', icon: 'chart', roles: ['ADMIN'] },
  { href: '/panel/jackpot-history', label: 'Historial Jackpot', icon: 'history', roles: ['ADMIN'] },
  { href: '/panel/notifications', label: 'Notificaciones', icon: 'bell', roles: ['ADMIN'] },
  { href: '/panel/admins', label: 'Admins', icon: 'admin', roles: ['ADMIN'] },
  { href: '/panel/logs', label: 'Logs', icon: 'list', roles: ['ADMIN'] },
  { href: '/panel/system', label: 'Sistema', icon: 'gear', roles: ['ADMIN'] },
  { href: '/panel/reports', label: 'Reportes', icon: 'report', roles: ['ADMIN'] },
  { href: '/panel/support', label: 'Soporte', icon: 'help', roles: ['ADMIN'] },
  { href: '/panel/worker-dashboard', label: 'Worker', icon: 'worker', roles: ['ADMIN_WORKER'] },
  { href: '/panel/worker-users', label: 'Usuarios (W)', icon: 'user', roles: ['ADMIN_WORKER'] },
  { href: '/panel/worker-quizzes', label: 'Quizzes (W)', icon: 'quiz', roles: ['ADMIN_WORKER'] },
  { href: '/panel/worker-withdrawals', label: 'Retiros (W)', icon: 'money', roles: ['ADMIN_WORKER'] },
  { href: '/panel/worker-audit', label: 'Auditoría', icon: 'audit', roles: ['ADMIN_WORKER'] },
  { href: '/panel/change-password', label: 'Contraseña', icon: 'lock', roles: ['ADMIN', 'ADMIN_WORKER'] },
] as const;

export const ADMIN_HIDDEN_SCREENS = [
  'change-password',
  'jackpot-history',
  'payments',
  'season-jackpot-distribution',
  'worker-users',
  'worker-quizzes',
  'worker-withdrawals',
  'worker-support',
  'worker-profile',
  'worker-audit',
  'quizzes/[id]',
] as const;
