export const ADMIN_NAV_ITEMS = [
  // Dashboard first for both roles (sidebar filters by role)
  { href: '/panel/dashboard', label: 'Dashboard', icon: 'home', roles: ['ADMIN'] },
  { href: '/panel/worker-dashboard', label: 'Dashboard', icon: 'home', roles: ['ADMIN_WORKER'] },
  { href: '/panel/users', label: 'Usuarios', icon: 'user', roles: ['ADMIN'] },
  { href: '/panel/worker-users', label: 'Usuarios', icon: 'user', roles: ['ADMIN_WORKER'] },
  { href: '/panel/quizzes', label: 'Quizzes', icon: 'quiz', roles: ['ADMIN', 'ADMIN_WORKER'] },
  { href: '/panel/posts', label: 'Moderación', icon: 'list', roles: ['ADMIN', 'ADMIN_WORKER'] },
  { href: '/panel/kyc', label: 'KYC', icon: 'shield', roles: ['ADMIN'] },
  { href: '/panel/payments', label: 'Pagos', icon: 'card', roles: ['ADMIN'] },
  { href: '/panel/financial', label: 'Finanzas', icon: 'money', roles: ['ADMIN'] },
  { href: '/panel/seasons', label: 'Temporadas', icon: 'trophy', roles: ['ADMIN', 'ADMIN_WORKER'] },
  { href: '/panel/quiz-distribution', label: 'Reparto Quiz', icon: 'chart', roles: ['ADMIN'] },
  { href: '/panel/messages', label: 'Mensajes', icon: 'bell', roles: ['ADMIN', 'ADMIN_WORKER'] },
  { href: '/panel/notifications', label: 'Notificaciones', icon: 'bell', roles: ['ADMIN'] },
  { href: '/panel/admins', label: 'Admins', icon: 'admin', roles: ['ADMIN'] },
  { href: '/panel/admin-access', label: 'Acceso panel', icon: 'lock', roles: ['ADMIN'] },
  { href: '/panel/logs', label: 'Logs', icon: 'list', roles: ['ADMIN'] },
  { href: '/panel/system', label: 'Sistema', icon: 'gear', roles: ['ADMIN'] },
  { href: '/panel/reports', label: 'Reportes', icon: 'report', roles: ['ADMIN'] },
  { href: '/panel/content', label: 'Contenido', icon: 'list', roles: ['ADMIN'] },
  { href: '/panel/support', label: 'Soporte', icon: 'help', roles: ['ADMIN'] },
  { href: '/panel/worker-withdrawals', label: 'Retiros', icon: 'money', roles: ['ADMIN_WORKER'] },
  { href: '/panel/worker-audit', label: 'Auditoría', icon: 'audit', roles: ['ADMIN_WORKER'] },
  { href: '/panel/worker-profile', label: 'Mi perfil', icon: 'lock', roles: ['ADMIN_WORKER'] },
  { href: '/panel/change-password', label: 'Mi contraseña', icon: 'lock', roles: ['ADMIN'] },
] as const;

/** Rutas del panel permitidas a ADMIN_WORKER (además de auth). El resto redirige a worker-dashboard. */
export const WORKER_ALLOWED_PATH_PREFIXES = [
  '/panel/worker-dashboard',
  '/panel/worker-users',
  '/panel/worker-quizzes',
  '/panel/worker-withdrawals',
  '/panel/worker-audit',
  '/panel/worker-profile',
  '/panel/worker-support',
  '/panel/quizzes',
  '/panel/seasons',
  '/panel/messages',
  '/panel/posts',
  '/panel/moderation-ban',
] as const;

export const ADMIN_HIDDEN_SCREENS = [
  'change-password',
  'admin-access',
  'jackpot-history',
  'season-jackpot-distribution',
  'worker-users',
  'worker-quizzes',
  'worker-withdrawals',
  'worker-support',
  'worker-profile',
  'worker-audit',
  'moderation-ban',
  'quizzes/[id]',
] as const;
